apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: alb-test
spec:
  scheme: internal
  ipAddressType: ipv4
  targetType: ip
  namespaceSelector:
    matchLabels: {}
  group:
    name: alb-test
  listeners:
    - protocol: HTTPS
      port: 443
  sslPolicy: ELBSecurityPolicy-TLS13-1-3-2021-06
  wafv2AclName: brave-alb
  loadBalancerAttributes:
    - key: idle_timeout.timeout_seconds
      value: "60"
  tags:
    - key: app
      value: alb-test
