apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alb-test

resources:
  - namespace.yaml
  - ingressclass.yaml
  - ingressclassparams.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
